### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by mikedupuis** [mikedupuis/happytab#10]
Add more info to the readme.

**Comment by ghost** [comment]
on it!

**Comment by aditya1rawat** [comment]
Can I do anything here?

**Comment by mikedupuis** [comment]
Yes! You could describe the existing features: links are generated from the user's bookmarks, the sidebar can be toggled on and off, and the items on the sidebar can be toggled on and off. Existing sidebar items are weather for the user's zipcode (zipcode is configurable),  quote of the day, and clock.

**Comment by Ludo05** [comment]
Is this still open for contribution?

**Comment by mikedupuis** [comment]
Yes, README.md improvements are always welcome!

**Comment by Ludo05** [comment]
Great I have opened a PR :)

**Comment by Ludo05** [comment]
Do you also need any updates or features updated. I'm very new to doing PR's but i'll be happy to help!

**Comment by mikedupuis** [comment]
This is really good! One other thing that would be good to add in the README.md would be a link to the extension on the Chrome Web Store: https://chrome.google.com/webstore/detail/happytab/pfncgbifkmheijfeckfhmkeghcjfgifa

Also, please feel free to update CONTRIBUTORS.md with a link to your GitHub profile.

I'll wait for an update (either additional commit(s) or a message saying you don't intend to make any more updates) from you before accepting your PR.

As far as updates and features, I don't have any really awesome ideas in the pipeline right now. One thing that would be cool would be to show/hide weather options based on the "show weather" toggle. That is, if "show weather" is off, hide the weather units, zipcode, and API key options. The same applies to NFL options.

**Comment by Ludo05** [comment]
I have updated the README.md and CONTRIBUTORS.md ready for approval! Cool, that sounds like something I should be able to do. Would you be able to open it as a separate issue and assign to me :)
