### ISSUE TITLE
Add Upcoming Birthdays

### ISSUE THREAD

**Issue by mikedupuis** [mikedupuis/happytab#11]
Add a feature to show upcoming birthdays.

1. Birthday data could integrate with a calendar app (e.g. Google Calendar), or could be user-configured.
2. Birthdays should be displayed when they are within the next X (configurable) days.

**Comment by gcmartins11** [comment]
I'm working on it!

**Comment by mikedupuis** [comment]
Closing this topic due to inactivity.
