### ISSUE TITLE
Hide Weather options when Show Weather is set to Off

### ISSUE THREAD

**Issue by mikedupuis** [mikedupuis/happytab#34]
When the "Show Weather" option is turned off (or on), hide (or show) the "Weather Units", "Weather Zipcode" and "OpenWeatherMap API Key" options.

**Comment by Ludo05** [comment]
I can pick this up :)

**Comment by Ludo05** [comment]
Opened a PR

**Comment by Ludo05** [comment]
Updated PR and left comment.

**Comment by Ludo05** [comment]
Another Update and comment :)
