### ISSUE TITLE
Update Screenshots

### ISSUE THREAD

**Issue by mikedupuis** [mikedupuis/happytab#45]
Update the screenshots used on the README.md. This would include both the new tab page example and the options.

**Comment by theballmarcus** [comment]
Im not it :)

**Comment by theballmarcus** [comment]
Well - I cant get the api key to work...

**Comment by mikedupuis** [comment]
You should be able to get an API key here: https://home.openweathermap.org/users/sign_up

**Comment by theballmarcus** [comment]
Yeah but I keep getting 401 error.

**Comment by CLOEI** [comment]
may I be assigned?, if yes do you just need me to replace the image from readme into my own screenshot of the tab and the option?

**Comment by theballmarcus** [comment]
They should be replaced with #46
