### ISSUE TITLE
Improve styling

### ISSUE THREAD

**Issue by mikedupuis** [mikedupuis/happytab#6]
Update CSS to make the extension look nicer

**Comment by thekanbo** [comment]
I can work on this!

**Comment by sonakollarova5** [comment]
Can I work on this issue?

**Comment by mikedupuis** [comment]
Absolutely! Feel free to make tweaks and improvements.

**Comment by galvc** [comment]
Hi, I'd like to help, do you have any ideas or general direction on the styling? Or is it just a general clean-up?

**Comment by mikedupuis** [comment]
I don't have a lot of specific thoughts on this. I'm not a front-end person, so I don't know all of the best practices in this realm and I'm open to suggestions. One idea would be to add tooltips for the various options in the options page.

**Comment by mikedupuis** [comment]
On the topic of tooltips, here is the documentation for Material Design Lite Tooltips: https://getmdl.io/components/#tooltips-section

**Comment by galvc** [comment]
Ok gotcha, thanks for the link, I was able to implement it.

And just to be sure, I will be helping style both the happytab page and options, right?

**Comment by mikedupuis** [comment]
I think there are opportunities for both. With respect to tooltips, I think those will be best on the options page (I don't think they're needed on the happytab page, necessarily). If you want to make some tweaks to the happytab styles, there are some opportunities there too:

1. I think the hover style for the links could be improved. The one I have is copied from the internet
2. If the boxes in the main part of the form were arranged with [masonry](https://masonry.desandro.com/), then they would look nicer when a user has several lists of bookmarks of different sizes.
3. You feel free to play with the typography. Maybe different fonts look nicer, maybe the sizing can be tweaked for different elements?
4. The file structure is kind of a mess. It's not the most fun work, but it will make the project nicer.

Ultimately, I think you should feel empowered to make adjustments that you think are better. I'm open to suggestions across the board when it comes to styling.

**Comment by galvc** [comment]
Thanks for the guidance. I was able to make a few tweaks on both the happytab and options page. What is the best way to show you without making a PR first? Should I fork the project with the modified style changes? Let me know of the best way to do this, thanks!

**Comment by mikedupuis** [comment]
> Should I fork the project with the modified style changes?

That will be fine, then you'll be ready to submit your PR after I take a look :)

Alternately, screenshots of the changed components will be fine.

**Comment by mikedupuis** [comment]
@galvc if you wish, please feel free to make a PR with a change to contributors.md with a link to your github profile.
